language: go

go:
  - "1.11.x"

env:
  global:
    - GO111MODULE=on
    - TEST_DB_DSN='root@tcp(127.0.0.1:3306)/kir_test?charset=utf8mb4&parseTime=true&loc=Local'

services:
  - mysql

before_script:
  - mysql -e 'drop database if exists kir_test;'
  - mysql -e 'create database kir_test;'

install:
  - go mod download

script:
  - go test -v ./...
